// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzmCLyVX2A5jBfLemw4eQD3vGpM_Z8TAA',
    appId: '1:242383005232:web:98024c60d10e61c4edaff5',
    messagingSenderId: '242383005232',
    projectId: 'project-money-laundry',
    authDomain: 'project-money-laundry.firebaseapp.com',
    storageBucket: 'project-money-laundry.firebasestorage.app',
    measurementId: 'G-Q3FYBK8SLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhkM9ksX0fIF5oBNlYs91qnEpl3VR6GqA',
    appId: '1:242383005232:android:1f98931bd40e9950edaff5',
    messagingSenderId: '242383005232',
    projectId: 'project-money-laundry',
    storageBucket: 'project-money-laundry.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe0Zs9z5dAjA1JNIjLwU05T4LnxO6G_4s',
    appId: '1:242383005232:ios:5983c5d7826ae5fcedaff5',
    messagingSenderId: '242383005232',
    projectId: 'project-money-laundry',
    storageBucket: 'project-money-laundry.firebasestorage.app',
    iosBundleId: 'com.example.moneyLaundry',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe0Zs9z5dAjA1JNIjLwU05T4LnxO6G_4s',
    appId: '1:242383005232:ios:5983c5d7826ae5fcedaff5',
    messagingSenderId: '242383005232',
    projectId: 'project-money-laundry',
    storageBucket: 'project-money-laundry.firebasestorage.app',
    iosBundleId: 'com.example.moneyLaundry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzmCLyVX2A5jBfLemw4eQD3vGpM_Z8TAA',
    appId: '1:242383005232:web:eb6f7d6578b8b4caedaff5',
    messagingSenderId: '242383005232',
    projectId: 'project-money-laundry',
    authDomain: 'project-money-laundry.firebaseapp.com',
    storageBucket: 'project-money-laundry.firebasestorage.app',
    measurementId: 'G-BZ6F2QX07C',
  );
}
