// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl6D9xw1tvwyWEBwKI-_LtxUbEYEnKytM',
    appId: '1:492490046863:web:70e60c9ade4963e7ee9ffa',
    messagingSenderId: '492490046863',
    projectId: 'money-laundry-2253a',
    authDomain: 'money-laundry-2253a.firebaseapp.com',
    storageBucket: 'money-laundry-2253a.firebasestorage.app',
    measurementId: 'G-L5ZQ2BFFC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPD0FAyURH9vz0JMMvq641wI-lTSjKb9o',
    appId: '1:492490046863:android:e04b95c2b4a75bf2ee9ffa',
    messagingSenderId: '492490046863',
    projectId: 'money-laundry-2253a',
    storageBucket: 'money-laundry-2253a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuopzWy_PPCA2rA1sfa102Icj2mRFaxPw',
    appId: '1:492490046863:ios:a4e79b6bf41ecd39ee9ffa',
    messagingSenderId: '492490046863',
    projectId: 'money-laundry-2253a',
    storageBucket: 'money-laundry-2253a.firebasestorage.app',
    iosBundleId: 'com.example.moneyLaundry',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuopzWy_PPCA2rA1sfa102Icj2mRFaxPw',
    appId: '1:492490046863:ios:a4e79b6bf41ecd39ee9ffa',
    messagingSenderId: '492490046863',
    projectId: 'money-laundry-2253a',
    storageBucket: 'money-laundry-2253a.firebasestorage.app',
    iosBundleId: 'com.example.moneyLaundry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl6D9xw1tvwyWEBwKI-_LtxUbEYEnKytM',
    appId: '1:492490046863:web:8e9d6d473f3bc471ee9ffa',
    messagingSenderId: '492490046863',
    projectId: 'money-laundry-2253a',
    authDomain: 'money-laundry-2253a.firebaseapp.com',
    storageBucket: 'money-laundry-2253a.firebasestorage.app',
    measurementId: 'G-RN0E2ZFRJL',
  );
}
